-keep class * extends androidx.fragment.app.Fragment{}
-keep class com.danil.kleshchin.rss.data.feeds.features.favorites.datasource.entity.* { *; }
-keep class com.danil.kleshchin.rss.data.feeds.features.feedslist.datasource.local.entity.* { *; }
-keep class com.danil.kleshchin.rss.data.feeds.features.feedslist.datasource.remote.entity.* { *; }
-keepnames class * extends java.io.Serializable
